name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read

jobs:
  specs:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
        include:
          - ruby: '3.4'
            coverage: 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: 'latest'

      - name: Install latest bundler
        run: |
          gem install bundler --no-document
          bundle config set without 'tools benchmarks docs'

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Run all tests
        env:
          GITHUB_COVERAGE: ${{ matrix.coverage }}
        run: bundle exec rspec

      - name: Run RuboCop
        if: matrix.ruby == '3.4'
        run: bundle exec rubocop

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    if: always()
    needs:
      - specs
    steps:
      - name: Check all jobs passed
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'skipped')
        run: exit 1
      - run: echo "All CI checks passed!"